# Generated by Django 6.0.2 on 2026-05-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Текст заговолок')),
                ('desc', models.TextField(verbose_name='Текст описание')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
