# Generated by Django 6.0.4 on 2026-05-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-id'], 'verbose_name': 'отзыв на товар', 'verbose_name_plural': 'Отзывы на товары'},
        ),
    ]
